language: java
branches:
  only:
    - main
    - develop

sudo: false

before_install:
  - chmod a+x ./gradlew

script:
  - ./gradlew --version
  - ./gradlew check 
  # - sonar-scanner
  - ./gradlew jacocoTestReport coveralls
  # - ./gradlew sonarqube
  - ./gradlew asciidoctor

  
after_success:
  - ./gradlew bootJar
  - ./gradlew asciidoctor
  - curl -F 'json_file=@build/coveralls/report.json' 'https://coveralls.io/api/v1/jobs'