name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Get permission for gradle wrapper
        run: chmod a+x ./gradlew
      - name: Check with Gradle
        run: ./gradlew check 
      - name: Generate coverage data for coveralls 
        run: ./gradlew jacocoTestReport coveralls
      - name: Generate jar 
        run: ./gradlew bootJar
      - name: Generate documentation
        run: ./gradlew asciidoctor
      - name: Send data to coveralls
        run: curl -F 'json_file=@build/coveralls/report.json' 'https://coveralls.io/api/v1/jobs'